/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'andrewmcglathery' at '8/5/15 10:43 PM' with Gradle 2.4
 *
 * @author andrewmcglathery, @date 8/5/15 10:43 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
